### ISSUE TITLE
Add other languages support

### ISSUE THREAD

**Issue by shall-git** [thomasneff/LiveSplit.CrashNSTLoadRemoval#1]
It's possible to add support for any language? It works only for english since is watching for 'LOADING' text. 
A configuration tab in witch you can upload in a specific format the screen/text to watch for might be the best.

**Comment by thomasneff** [comment]
Yes, it would be possible to add support for other languages, but not without a ton of manual effort. Getting the load remover to work as reliably as it does right now for the english version required collecting ~1200 images from different capture setups, resolutions, layouts, etc., to be able to cover most setups that people use. Each different language would require the same amount of effort, basically requiring dozens of work hours collecting data and testing the functionality. Especially with languages that are not commonly used in streams/speedruns, it will be difficult to collect sufficient data to ensure the reliability of the detection.

So for now - no, this will not be implemented from my side in the near future. I might have time to rework the tool to allow for easier capturing of images and creating new feature databases, which would allow anyone to create databases for the different languages. However, this is also a lot of effort and will probably not be done by me soon.
